# This workflow will install python 3.6, dependencies, and run tests with pytest

name: Python application
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        ./setup.sh
    - name: Test with pytest
      env:
        KEY_ID: ${{ secrets.KEY_ID }}
        SECRET_KEY_ID: ${{ secrets.SECRET_KEY_ID }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        ENVIRONMENT: github_actions
      run: |
        venv/bin/pytest
